In [1]:
!pip install sqlalchemy
!pip install psycopg2
!pip install psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.6/dist-packages (1.3.13)
Requirement already satisfied: psycopg2 in /usr/local/lib/python3.6/dist-packages (2.7.6.1)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.6/dist-packages (2.8.4)

In [0]:
# Import the SQL ALchemy engine
from sqlalchemy import create_engine

# Database credentials
postgres_user = 'dsbc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'medicalcosts'

# use the credentials to start a connection
engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))

In [5]:
# Use the connection to execute some SQL
insurance = engine.execute('SELECT * FROM medicalcosts LIMIT 10')

# no need for an open connection, as we're only doing a single query
engine.dispose()

# Process the results
for row in insurance:
  print(row)

(19, 'female', 27.9, 0, 'yes', 'southwest', 16884.9)
(18, 'male', 33.77, 1, 'no', 'southeast', 1725.55)
(28, 'male', 33.0, 3, 'no', 'southeast', 4449.46)
(33, 'male', 22.705, 0, 'no', 'northwest', 21984.5)
(32, 'male', 28.88, 0, 'no', 'northwest', 3866.86)
(31, 'female', 25.74, 0, 'no', 'southeast', 3756.62)
(46, 'female', 33.44, 1, 'no', 'southeast', 8240.59)
(37, 'female', 27.74, 3, 'no', 'northwest', 7281.51)
(37, 'male', 29.83, 2, 'no', 'northeast', 6406.41)
(60, 'female', 25.84, 0, 'no', 'northwest', 28923.1)

In [6]:
# get a list of the keys (column names) 
insurance.keys()

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

In [0]:
# Access it by position
bmi = first_row['bmi']

# Access if by column name
charges = first_row['charges']

print('The first row has a bmi of {} and charges of {}'.format(bmi, charges))